### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Bimbelhuber** [ihrigb/node-red-contrib-doorbird-ultimate#10]
Can you help me to install the nodes? Following te discription from te Viewlog:

2022-10-12T12:21:06.442Z installieren : node-red-contrib-doorbird-ultimate 1.1.1
2022-10-12T12:21:07.432Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production [node-red-contrib-doorbird-ultimate@1.1.1](mailto:node-red-contrib-doorbird-ultimate@1.1.1)
2022-10-12T12:21:17.202Z [out] 
2022-10-12T12:21:17.202Z [out] up to date in 9s
2022-10-12T12:21:17.228Z rc=0

**Comment by Bimbelhuber** [comment]
Hi @ihrigb,

ich schreibs mal auf deutsch, das sollte ich glaub auch funktionieren ;)

Nachfolgend die Fehlermeldung (Bild) bei der Installation, es sind also auch keine Nodes zu sehen, der View log bleibt immer noch der Selbe:
![image](https://user-images.githubusercontent.com/115694216/195568446-c1cb9b42-3cde-4bbc-8af6-c6119b881dc6.png)

2022-10-13T10:08:54.130Z installieren : node-red-contrib-doorbird-ultimate 1.1.1

2022-10-13T10:08:54.412Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-doorbird-ultimate@1.1.1
2022-10-13T10:09:01.132Z [out] 
2022-10-13T10:09:01.132Z [out] up to date in 6s
2022-10-13T10:09:01.158Z rc=0

**Comment by ihrigb** [comment]
Deutsch ist ok. Ich könnte mir vorstellen, dass er das `nodes` property im package.json meint: https://github.com/ihrigb/node-red-contrib-doorbird-ultimate/blob/master/package.json#L26. Aber warum er das nicht findet, verstehe ich nicht wirklich. Welche Version von Node Red betreibst du denn wo / wie?

**Comment by Bimbelhuber** [comment]
Also bisher haben alle Installationen von Nodes funktioniert. Also Hardware habe ich eine Homematic CCU3 (FW 3.65.8) worauf RedMatic mit Version 7.2.1 läuft.
Gibt es  denn eine andere Möglichkeit die Installation zu probieren als über die von mir gewählte?

**Comment by ihrigb** [comment]
Ich habe die nodes eigentlich für Node Red >=2.0.0 angegeben. Ich habe leider keine Zeit, zu schauen, ob es mit allem, was älter ist einwandfrei läuft. Zudem kann ich mir vorstellen, dass es Probleme mit den Crypto Komponenten (libsodium) gibt. Da weiß icht nicht, was auf der CCU verfügbar ist, bzw. die Voraussetzungen sind.
Welche anderen Packages hast du denn installiert, dann vergleiche ich mal!

**Comment by Bimbelhuber** [comment]
Entweder ich bin zu doof aber ich kann nicht heraus finden wie, bzw. ob ich NodeRed auf RedMatic updaten kann, zumal RedMatic die aktuelle Version ist.
Installierte Packages:
![image](https://user-images.githubusercontent.com/115694216/195593484-0c99bf27-80c1-44f2-b149-2fe013ce090e.png)
![image](https://user-images.githubusercontent.com/115694216/195593556-3dd879c6-6546-41b9-bd68-228ff1ecdfdc.png)
![image](https://user-images.githubusercontent.com/115694216/195593628-dfb2544a-71fa-46be-89e7-e459ff9cdf50.png)

**Comment by Bimbelhuber** [comment]
Servus, konntest du schon was heraus finden? Danke!

**Comment by ihrigb** [comment]
Sorry, nein ich bin noch nicht dazu gekommen.

**Comment by ihrigb** [comment]
Das wäre ein Hinweis auf das Problem: https://github.com/rdmtc/RedMatic/issues/146#issuecomment-460039906
Heißt RedMatic hat die Sodium binaries nicht.

**Comment by Bimbelhuber** [comment]
Servus Hallo, nach dem neuesten Release deines Pakets kann ich es nun auch installieren 👍 Aber ich bekomme es noch nicht hin das Ring Node so mit der Alexa zu verbinden das diese was ausgeben kann. Kannst du mir einen Tipp geben wie ich das Signal manipulieren muss das es passt. Als payload würde mir ein einfaches true oder false reichen, aber die Ausgabe des Ring Node liefert ja noch viel mehr Informationen, danke dir schonmal vorab!

**Comment by Bimbelhuber** [comment]
Perfekt, danke!
