### ISSUE TITLE
Ring and Motion does not work

### ISSUE THREAD

**Issue by HollaTheWoodFairy** [ihrigb/node-red-contrib-doorbird-ultimate#12]
Hi, i've fresh installed this plugin and tested for a while but i do not get any ring or motion feedback.
I've also tested the info function and this gives me the expected output in the debugging view.

What i try to do is to give me a debugging message when i press the ring button or use the motion sensor. Do you know what i'm doing wrong? Maybe it's a bug because of the authentication is working because of i do get feedback from the info function.

![image](https://user-images.githubusercontent.com/82179494/211204476-851c4163-31db-4025-8fe4-26e0fe61beae.png)

**Comment by HollaTheWoodFairy** [comment]
Fond the issue. It's about the docker container where node red is running. It seems that it does not pass through the needed ports.

**Comment by ihrigb** [comment]
Yep, would have been my first question. Docker bridge networks do not allow UDP broadcasts to go through. I have plans to move the whole communication on http (register a http event in Doorbird). But nothing scheduled yet.
