### ISSUE TITLE
Doorbird-open edit dialogue does not show relays

### ISSUE THREAD

**Issue by Tom1000** [ihrigb/node-red-contrib-doorbird-ultimate#13]
When I open the edit dialogue in node-re editor to configure a Doorbird-Open node, no relay is shown.

Here is what is working: 
- Global config node works, device is configured
- An Doorbird-Info node works as well, the message shows the relays for which the user has permissions
- If I manually edit [doorbird-open.html](https://github.com/ihrigb/node-red-contrib-doorbird-ultimate/blob/main/nodes/doorbird-open.html), change the [input](https://github.com/ihrigb/node-red-contrib-doorbird-ultimate/blob/main/nodes/doorbird-open.html#L73) to input text and remove the ajax call, I can manually enter the relay and everything works fine.

I did some more trouble-shooting and it looks like the [ajax call](https://github.com/ihrigb/node-red-contrib-doorbird-ultimate/blob/main/nodes/doorbird-open.html#L38) does not work. After entering oneditprepare and when the function updateRelays is called, the browser never gets past the ajax call.

--------------------------------
node-red-contrib-doorbird-ultimate version: 1.2.0 (latest)
node-doorbird version: 2.0.1 (latest)
Node-red version: 3.0.2 (latest stable)

I can reproduce the issue on a second node-red instance (but on the same network).

**Comment by ihrigb** [comment]
Thanks for reporting, I can confirm the bug. Fix will follow!

**Comment by ihrigb** [comment]
Fix published in Version 1.2.1.

**Comment by Tom1000** [comment]
Wow, that was quick. Thank you!
