### ISSUE TITLE
No output for ring events

### ISSUE THREAD

**Issue by bifbaf** [ihrigb/node-red-contrib-doorbird-ultimate#15]
Hi,
I am using a bunch of the nodes in my setup and all are working fine except the ring node.
My debug output did not show anything if someone put the ring button on the doorbird.
Permissions for the user are correct. The user have the api-operator permission. I don't think that anything else is necessary.

Could you please check this issue?
I am using the latest version 1.2.1

**Comment by ihrigb** [comment]
@bifbaf do you maybe run Node Red in a Docker container environment? Depending on the network configuration, the UDP broadcast will not reach the container runtime.

**Comment by bifbaf** [comment]
I am running node red together with HASSOS. So it is probably the same. Is there any way to resolve this kind of issue?

**Comment by ihrigb** [comment]
You can use a host network and I believe MACVLAN should do it as well. Bridge networks won't forward UDP broadcasts to the container.

**Comment by bifbaf** [comment]
Mh don‘t know how to do this with hassos because it is not a container that I can simply restart as host network. I will figure it out how to do it. Thanks for your help. As this seem not to be an issue with your integration you can close that issue 🙂
