### ISSUE TITLE
Node red restarts after each doorbird interaction

### ISSUE THREAD

**Issue by WernerMa96** [ihrigb/node-red-contrib-doorbird-ultimate#25]
Hey, 
since my update to node red 3 and node.js 20 i have good a big issue. Everytime a doorbird event happen (ring, motion) my node red crashes and restarts.

Log:
`
> Dec  1 14:17:36 raspberrypi Node-RED[68393]: 1 Dec 14:17:36 - [red] Uncaught Exception:
> Dec  1 14:17:36 raspberrypi Node-RED[68393]: 1 Dec 14:17:36 - [error] TypeError: sodium.crypto_pwhash is not a function
> Dec  1 14:17:36 raspberrypi Node-RED[68393]:     at DoorbirdUdpSocket.<anonymous> (/home/pi/.node-red/node_modules/doorbird/dist/index.js:121:55)
> Dec  1 14:17:36 raspberrypi Node-RED[68393]:     at step (/home/pi/.node-red/node_modules/doorbird/dist/index.js:56:23)
> Dec  1 14:17:36 raspberrypi Node-RED[68393]:     at Object.next (/home/pi/.node-red/node_modules/doorbird/dist/index.js:37:53)
> Dec  1 14:17:36 raspberrypi Node-RED[68393]:     at fulfilled (/home/pi/.node-red/node_modules/doorbird/dist/index.js:28:58)
> Dec  1 14:17:36 raspberrypi systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
> Dec  1 14:17:36 raspberrypi systemd[1]: nodered.service: Failed with result 'exit-code'.
> Dec  1 14:17:36 raspberrypi systemd[1]: nodered.service: Consumed 1h 8min 20.425s CPU time.
> Dec  1 14:17:56 raspberrypi systemd[1]: nodered.service: Scheduled restart job, restart counter is at 30.
> Dec  1 14:17:56 raspberrypi systemd[1]: Stopped Node-RED graphical event wiring tool.
> Dec  1 14:17:56 raspberrypi systemd[1]: nodered.service: Consumed 1h 8min 20.425s CPU time.
`

Is this an known issue? What can i do?

Best regards!

**Comment by ihrigb** [comment]
@WernerMa96 can you provide more information on your system, runtime environment and so on?

**Comment by WernerMa96** [comment]
@ihrigb  i saw that i have a old version 1.2.1.
https://flows.nodered.org/node/node-red-contrib-doorbird-ultimate is it possible to update this version so i can update it via palette manager?

**Comment by ihrigb** [comment]
The latest version (1.3.0) should already be available via the palette manager.

**Comment by ihrigb** [comment]
@WernerMa96 I will close this issue, as I did not hear anything for three weeks. If the problem still remains, feel free to open another issue.
