### ISSUE TITLE
Please add a "Reboot device" function

### ISSUE THREAD

**Issue by Jan1503** [ihrigb/node-red-contrib-doorbird-ultimate#27]
Hi!

I'm a Home Assistant user and would like to use my Doorbird with Frigate.
Due to the fact that the Doorbird could be easily overloaded by too many/frequently requests I need to restart it 2 - 3 times a day.
This is currently not possible with the official implementation although the api-endpoint exists.

Would you mind adding this function? Should be an easy tasks I guess, but I have no programming knowledge in this area.

Thanks and regards,
Jan

**Comment by ihrigb** [comment]
Available as of the [1.4.0](https://github.com/ihrigb/node-red-contrib-doorbird-ultimate/releases/tag/v1.4.0) release.

**Comment by ihrigb** [comment]
It might take up to a day until Node Red discovered the new version. After that you will be able to update from the palette manager.
