### ISSUE TITLE
No video since upgrade

### ISSUE THREAD

**Issue by marnikvd** [ihrigb/node-red-contrib-doorbird-ultimate#29]
Hello,

Node-red is running in a [docker container](https://hub.docker.com/r/nodered/node-red) with [node-red-contrib-doorbird-ultimate](https://github.com/ihrigb/node-red-contrib-doorbird-ultimate) version 1.4.0

Everything works fine except [video](https://github.com/ihrigb/node-red-contrib-doorbird-ultimate?tab=readme-ov-file#ui-video)
It worked before but I have the impression it stopped working since I installed the latest version of node-red-contrib-doorbird-ultimate.

This is what I noticed :
In the file `/data/node-modules/doorbird/dist/index.js` in the function `Doorbird.prototype.getVideoUrl` there is a line
`var baseUri = "http://".concat(this.options.host, "/bha-api/audio-receive.cgi");`
I changed this to
`var baseUri = "http://".concat(this.options.host, "/bha-api/video.cgi");`
After restarting the container I get the video in the ui, but it doesn't render like it should (there is a vertical scroll bar !) so there is more to it.
![Schermafbeelding 2024-01-02 110904](https://github.com/ihrigb/node-red-contrib-doorbird-ultimate/assets/15088944/52abb293-1ca3-4938-8ea0-aeb6b49b2377)

Is there someone (who knows what he is doing :wink:) who can solve this ?

thanks.

**Comment by ihrigb** [comment]
I will look into it.

**Comment by ihrigb** [comment]
I will look into it.

**Comment by ihrigb** [comment]
https://github.com/ihrigb/node-doorbird/issues/204

**Comment by marnikvd** [comment]
When I set the Size to auto I get the rendering from my first post.
![image](https://github.com/ihrigb/node-red-contrib-doorbird-ultimate/assets/15088944/73475950-7e1a-4b78-adb2-9f7a84dfcccc)
When I set it to 6x6 it is like yours.  I don't know if this is the intended behaviour.

**Comment by marnikvd** [comment]
6x5 is also fine

**Comment by ihrigb** [comment]
Mine is on auto... I will try to experiment with it.

**Comment by marnikvd** [comment]
I noticed something strange :
The layout button of the dashboard tab is erroneous.  This is only the case where the video widget resides.
![image](https://github.com/ihrigb/node-red-contrib-doorbird-ultimate/assets/15088944/c9eb672a-fc81-4fc2-817f-d8d2458e88eb)

**Comment by marnikvd** [comment]
I isolated a test case :

https://github.com/ihrigb/node-red-contrib-doorbird-ultimate/assets/15088944/91094fc2-7047-4321-8f6f-64f9b477cb51

**Comment by ihrigb** [comment]
I finally got to test this again, and it is working fine for me.
