### ISSUE TITLE
doorbird open

### ISSUE THREAD

**Issue by dianaw1977** [ihrigb/node-red-contrib-doorbird-ultimate#4]
When I connect a button to the doorbird open and press the button, I get the following error:

12/13/2021, 12:01:20 PMnode: doorbirdopen
msg : string[39]
"Doorbird Station returned invalid JSON."

**Comment by ihrigb** [comment]
@dianaw1977 the node is currently in development. I will take care of it and let you know, once this works.

**Comment by ihrigb** [comment]
@dianaw1977 is there a chance that you provide log output? The code has two console log statemants for the response and the body. Maybe you can provide it?

**Comment by dianaw1977** [comment]
> 

Hi ihrign, when i check this log: journalctl -f -u nodered -o cat

I only see these lines:

13 Dec 14:03:40 - [info] Started flows
13 Dec 14:03:40 - [info] [mqtt-broker:homey] Connected to broker: mqtt://xxx.xx.xx.xx:1883
13 Dec 14:04:05 - [error] [doorbird-open:doorbirdopen] Doorbird Station returned invalid JSON

Is there another location where i can find additional logging.

regards,

Diana

**Comment by ihrigb** [comment]
Hi, no I believe not. As opening the door is actually working for me lets do it the following way: I will improve logging and put out a new version and then we will see, what is actually going wrong.

**Comment by ihrigb** [comment]
@dianaw1977 new version is out (0.0.4)

**Comment by dianaw1977** [comment]
> @dianaw1977 new version is out (0.0.4)

@ihrigb I updated to the new version and attached is the log output.

[logging_doorbird.txt](https://github.com/ihrigb/node-red-contrib-doorbird-ultimate/files/7706405/logging_doorbird.txt)

**Comment by ihrigb** [comment]
I added another change, that should do it. Can you please try and let me know, how the behavior changes?

**Comment by dianaw1977** [comment]
@ihrigb Yes that works. the gate opens. Thanks

**Comment by ihrigb** [comment]
Cool, thanks.
If you'd like to do me a favor, you could tell me, if the returned payload now contains a string, or a json object (just by a debugging node).

**Comment by dianaw1977** [comment]
Hi,  yes i got this response in the debugnode.

12/14/2021, 8:02:22 AM node: debugdoorbirdopen
msg.payload : Object
object
BHA: object
RETURNCODE: "1"
