### ISSUE TITLE
Ring and Motion dont trigger any events

### ISSUE THREAD

**Issue by Diddlik** [ihrigb/node-red-contrib-doorbird-ultimate#7]
I have set up the main node, it seems to work, see screenshot. But when it rings or there is movement, nothing is triggered. 
On motion or Ring is debug output empty:
![grafik](https://user-images.githubusercontent.com/6010713/190972682-3e1d30aa-83dd-46c4-9084-b4c6f82fdc56.png)

![grafik](https://user-images.githubusercontent.com/6010713/190972610-9147ac69-d0fe-4c1e-9ed3-61de3551ea5e.png)

**Comment by ihrigb** [comment]
Hi @Diddlik,
can you please share some details on how you run Node Red? (E.g. Docker bridged networks do not allow to receive UDP broadcasts).
Benjamin

**Comment by Diddlik** [comment]
I have nod-red in a docker but in host mode. At the moment I use this one node: "node-red-contrib-doorbird" with UDP from 6524 / 35344 and it works fine. But in long term my wish to use your node because of more functions.

**Comment by ihrigb** [comment]
Ok, then we might have a problem here. Can you see any details in the container logs?

**Comment by Diddlik** [comment]
I looked at the logs, there is nothing. 
Then triggered both events and the log has nothing done

**Comment by ihrigb** [comment]
Without any log that is very hard to trace. I still got log improvements on my todo list, so we may get better information on what is happening here. But for now, it is hard to understand, why Node Red's UDP node receives a message but the doorbird node does not (it would still log errors).

**Comment by ihrigb** [comment]
@Diddlik to be sure: Can you send me the logfile for node red?

**Comment by Diddlik** [comment]
@ihrigb Do you know how can I get a log from docker? At the moment a read it only with this command "docker logs nodered_docker_id"

**Comment by ihrigb** [comment]
Yep, `docker logs <name>` is the way to go.

**Comment by Diddlik** [comment]
In the time multiple time I triggered a motion or ring event

`22 Sep 00:00:00 - [info] [alexa-remote-account:AlexaPavel] intialising "AlexaPavel" with the PROXY method and saved data...
22 Sep 00:28:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 00:58:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 01:28:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 01:58:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 02:28:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 02:58:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 03:28:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 03:58:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 04:28:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 04:58:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 05:28:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 05:58:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 06:28:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 06:58:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 07:00:01 - [info] [e-mail in:KiTa] Error: Invalid credentials (Failure)
'notification update ended successfully...'
22 Sep 07:28:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 07:30:01 - [info] [e-mail in:KiTa] Error: Invalid credentials (Failure)
22 Sep 07:58:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 08:00:03 - [info] [e-mail in:KiTa] Error: Invalid credentials (Failure)
22 Sep 08:28:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 08:30:05 - [info] [e-mail in:KiTa] Error: Invalid credentials (Failure)
22 Sep 08:58:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 09:00:02 - [info] [e-mail in:KiTa] Error: Invalid credentials (Failure)
22 Sep 09:17:18 - [error] [influxdb out:York_v1_Prod] Error: A 400 Bad Request error occurred: {"error":"unable to parse 'Energy,sensor=total_energy state=NaN': invalid number"}

22 Sep 09:17:18 - [error] [influxdb out:York_v1_Prod] Error: A 400 Bad Request error occurred: {"error":"unable to parse 'Energy,sensor=active_power state=NaN': invalid number"}

22 Sep 09:28:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 09:30:01 - [info] [e-mail in:KiTa] Error: Invalid credentials (Failure)
22 Sep 09:39:30 - [error] [influxdb out:York_v1_Prod] Error: A 400 Bad Request error occurred: {"error":"unable to parse 'Energy,sensor=active_power state=NaN': invalid number"}

22 Sep 09:58:39 - [error] [api-current-state:Distance] Entity could not be found in cache for entity_id: sensor.0x00124b00087fe6f2_distance_in_mm
22 Sep 10:00:02 - [info] [e-mail in:KiTa] Error: Invalid credentials (Failure)
22 Sep 10:02:57 - [info] Stopping flows
22 Sep 10:02:57 - [info] [udp in:77723a32.bf68ec] udp listener stopped
22 Sep 10:02:57 - [info] [udp in:2698e39a.62826c] udp listener stopped
22 Sep 10:02:57 - [info] [server:ha-prod] Closing connection to http://ha-prod:8123
22 Sep 10:02:57 - [info] [ccu-connection:CCU3] regadata saved to /data/ccu_rega_192.168.1.4.json
22 Sep 10:02:57 - [info] [ccu-connection:CCU3] values saved to /data/ccu_values_192.168.1.4.json
22 Sep 10:02:57 - [info] [fritzbox-callmonitor:f0f6bd89.0d2f3] Disconnected from fritzbox
22 Sep 10:02:57 - [info] [ccu-connection:CCU3] de-init BidCos-RF http://192.168.1.50:2048 done
22 Sep 10:02:57 - [info] [ccu-connection:CCU3] de-init HmIP-RF http://192.168.1.50:2048 done
22 Sep 10:02:57 - [info] [ccu-connection:CCU3] de-init VirtualDevices http://192.168.1.50:2048 done
22 Sep 10:02:57 - [info] [ccu-connection:CCU3] xmlrpc server closed
22 Sep 10:02:57 - [info] [ccu-connection:CCU3] rpc close done
22 Sep 10:02:57 - [info] Stopped flows
22 Sep 10:02:57 - [info] Updated flows
22 Sep 10:02:57 - [info] Starting flows
22 Sep 10:02:57 - [info] Telegram Bot NodeRed Bot will be launched, environment is development
22 Sep 10:02:57 - [info] No context provider specified for chatbot NodeRed Bot. Defaulting to "memory"
22 Sep 10:02:57 - [info] [ccu-connection:CCU3] paramsets loaded from /data/paramsets.json
22 Sep 10:02:57 - [info] [ccu-connection:CCU3] metadata loaded from /data/ccu_192.168.1.4.json
22 Sep 10:02:57 - [info] [ccu-connection:CCU3] regadata loaded from /data/ccu_rega_192.168.1.4.json
22 Sep 10:02:57 - [info] [ccu-connection:CCU3] values loaded from /data/ccu_values_192.168.1.4.json
22 Sep 10:02:57 - [info] [fritzbox-callmonitor:f0f6bd89.0d2f3] Connecting to fritzbox...
22 Sep 10:02:57 - [info] Started flows
22 Sep 10:02:57 - [info] [udp in:77723a32.bf68ec] udp listener at 0.0.0.0:6524
22 Sep 10:02:57 - [info] [udp in:2698e39a.62826c] udp listener at 0.0.0.0:35344
22 Sep 10:02:57 - [info] [server:ha-prod] Connecting to http://ha-prod:8123
22 Sep 10:02:57 - [info] [fritzbox-callmonitor:f0f6bd89.0d2f3] Connected to fritzbox
22 Sep 10:02:57 - [info] [mqtt-broker:441f7494.97245c] Connected to broker: mqtt://192.168.1.50:1883
22 Sep 10:02:57 - [info] [mqtt-broker:mqtt] Connected to broker: mqtt://192.168.1.50:1883
22 Sep 10:02:57 - [info] [alexa-remote-account:AlexaPavel] intialising "AlexaPavel" with the PROXY method and saved data...
22 Sep 10:02:57 - [info]
22 Sep 10:02:57 - [info] ------ WebHooks for TELEGRAM----------------
22 Sep 10:02:57 - [info] http://localhost:1880/redbot/telegram/test
22 Sep 10:02:57 - [info] http://localhost:1880/redbot/telegram
22 Sep 10:02:57 - [info]
22 Sep 10:02:57 - [info] [server:ha-prod] Connected to http://ha-prod:8123
22 Sep 10:02:57 - [info] [ccu-connection:CCU3] rega getValues
22 Sep 10:02:58 - [info] [ccu-connection:CCU3] values saved to /data/ccu_values_192.168.1.4.json
22 Sep 10:02:58 - [info] [ccu-connection:CCU3] Interfaces: ReGaHSS, BidCos-RF, HmIP-RF, VirtualDevices
22 Sep 10:02:58 - [info] [ccu-connection:CCU3] Interface ReGaHSS connected
22 Sep 10:02:58 - [info] [ccu-connection:CCU3] init BidCos-RF http://192.168.1.50:2048 nr_L5KXKe_BidCos-RF
22 Sep 10:02:58 - [info] [ccu-connection:CCU3] init HmIP-RF http://192.168.1.50:2048 nr_L5KXKe_HmIP-RF
22 Sep 10:02:58 - [info] [ccu-connection:CCU3] init VirtualDevices http://192.168.1.50:2048 nr_L5KXKe_VirtualDevices
22 Sep 10:02:58 - [info] [ccu-connection:CCU3] xmlrpc server listening on http://192.168.1.50:2048
22 Sep 10:02:58 - [info] [ccu-connection:CCU3] Interface BidCos-RF http port 2001 connected
22 Sep 10:02:58 - [info] [ccu-connection:CCU3] regadata saved to /data/ccu_rega_192.168.1.4.json
22 Sep 10:02:58 - [info] [ccu-connection:CCU3] Interface HmIP-RF http port 2010 connected
22 Sep 10:02:58 - [info] [ccu-connection:CCU3] Interface VirtualDevices http port 9292 connected
22 Sep 10:02:58 - [info] [ccu-connection:CCU3] metadata saved to /data/ccu_192.168.1.4.json
22 Sep 10:02:58 - [info] [ccu-connection:CCU3] metadata saved to /data/ccu_192.168.1.4.json
22 Sep 10:03:07 - [info] [alexa-remote-account:AlexaPavel] intialising "AlexaPavel" with the PROXY method and saved data...
22 Sep 10:03:38 - [error] [influxdb out:York_v1_Prod] Error: A 400 Bad Request error occurred: {"error":"unable to parse 'Energy,sensor=total_energy state=NaN': invalid number"}

22 Sep 10:03:38 - [error] [influxdb out:York_v1_Prod] Error: A 400 Bad Request error occurred: {"error":"unable to parse 'Energy,sensor=active_power state=NaN': invalid number"}

22 Sep 10:06:34 - [info] Stopping flows
22 Sep 10:06:34 - [info] [udp in:77723a32.bf68ec] udp listener stopped
22 Sep 10:06:34 - [info] [udp in:2698e39a.62826c] udp listener stopped
22 Sep 10:06:34 - [info] [server:ha-prod] Closing connection to http://ha-prod:8123
22 Sep 10:06:34 - [info] [ccu-connection:CCU3] regadata saved to /data/ccu_rega_192.168.1.4.json
22 Sep 10:06:34 - [info] [ccu-connection:CCU3] values saved to /data/ccu_values_192.168.1.4.json
22 Sep 10:06:34 - [info] [fritzbox-callmonitor:f0f6bd89.0d2f3] Disconnected from fritzbox
22 Sep 10:06:34 - [info] [ccu-connection:CCU3] de-init BidCos-RF http://192.168.1.50:2048 done
22 Sep 10:06:34 - [info] [ccu-connection:CCU3] de-init HmIP-RF http://192.168.1.50:2048 done
22 Sep 10:06:34 - [info] [ccu-connection:CCU3] de-init VirtualDevices http://192.168.1.50:2048 done
22 Sep 10:06:36 - [error] [ccu-connection:CCU3] xmlrpc server close timeout
22 Sep 10:06:36 - [info] [ccu-connection:CCU3] rpc close done
22 Sep 10:06:36 - [info] Stopped flows
22 Sep 10:06:36 - [info] Updated flows
22 Sep 10:06:36 - [info] Starting flows
22 Sep 10:06:36 - [info] Telegram Bot NodeRed Bot will be launched, environment is development
22 Sep 10:06:36 - [info] No context provider specified for chatbot NodeRed Bot. Defaulting to "memory"
22 Sep 10:06:37 - [info] [ccu-connection:CCU3] paramsets loaded from /data/paramsets.json
22 Sep 10:06:37 - [info] [ccu-connection:CCU3] metadata loaded from /data/ccu_192.168.1.4.json
22 Sep 10:06:37 - [info] [ccu-connection:CCU3] regadata loaded from /data/ccu_rega_192.168.1.4.json
22 Sep 10:06:37 - [info] [ccu-connection:CCU3] values loaded from /data/ccu_values_192.168.1.4.json
22 Sep 10:06:37 - [info] [fritzbox-callmonitor:f0f6bd89.0d2f3] Connecting to fritzbox...
22 Sep 10:06:37 - [info] Started flows
22 Sep 10:06:37 - [info] [server:ha-prod] Connecting to http://ha-prod:8123
22 Sep 10:06:37 - [info] [fritzbox-callmonitor:f0f6bd89.0d2f3] Connected to fritzbox
22 Sep 10:06:37 - [info] [mqtt-broker:441f7494.97245c] Connected to broker: mqtt://192.168.1.50:1883
22 Sep 10:06:37 - [info] [alexa-remote-account:AlexaPavel] intialising "AlexaPavel" with the PROXY method and saved data...
22 Sep 10:06:37 - [info] [mqtt-broker:mqtt] Connected to broker: mqtt://192.168.1.50:1883
22 Sep 10:06:37 - [info]
22 Sep 10:06:37 - [info] ------ WebHooks for TELEGRAM----------------
22 Sep 10:06:37 - [info] http://localhost:1880/redbot/telegram/test
22 Sep 10:06:37 - [info] http://localhost:1880/redbot/telegram
22 Sep 10:06:37 - [info]
22 Sep 10:06:37 - [info] [server:ha-prod] Connected to http://ha-prod:8123
22 Sep 10:06:37 - [info] [ccu-connection:CCU3] rega getValues
22 Sep 10:06:37 - [info] [ccu-connection:CCU3] values saved to /data/ccu_values_192.168.1.4.json
22 Sep 10:06:37 - [info] [ccu-connection:CCU3] Interfaces: ReGaHSS, BidCos-RF, HmIP-RF, VirtualDevices
22 Sep 10:06:37 - [info] [ccu-connection:CCU3] Interface ReGaHSS connected
22 Sep 10:06:37 - [info] [ccu-connection:CCU3] init BidCos-RF http://192.168.1.50:2048 nr_L5KXKe_BidCos-RF
22 Sep 10:06:37 - [info] [ccu-connection:CCU3] init HmIP-RF http://192.168.1.50:2048 nr_L5KXKe_HmIP-RF
22 Sep 10:06:37 - [info] [ccu-connection:CCU3] init VirtualDevices http://192.168.1.50:2048 nr_L5KXKe_VirtualDevices
22 Sep 10:06:37 - [info] [ccu-connection:CCU3] xmlrpc server listening on http://192.168.1.50:2048
22 Sep 10:06:37 - [info] [ccu-connection:CCU3] Interface BidCos-RF http port 2001 connected
22 Sep 10:06:37 - [info] [ccu-connection:CCU3] regadata saved to /data/ccu_rega_192.168.1.4.json
22 Sep 10:06:37 - [info] [ccu-connection:CCU3] Interface HmIP-RF http port 2010 connected
22 Sep 10:06:37 - [info] [ccu-connection:CCU3] Interface VirtualDevices http port 9292 connected
22 Sep 10:06:37 - [info] [ccu-connection:CCU3] metadata saved to /data/ccu_192.168.1.4.json
22 Sep 10:06:38 - [info] [ccu-connection:CCU3] metadata saved to /data/ccu_192.168.1.4.json
22 Sep 10:06:38 - [info] [ccu-connection:CCU3] xmlrpc server closed
22 Sep 10:06:47 - [info] [alexa-remote-account:AlexaPavel] intialising "AlexaPavel" with the PROXY method and saved data...
`

**Comment by Diddlik** [comment]
Just made another test.

Under windows freshly installed node-red.
Then the doorbird node and motion and ring event triggered. Nothing im log 


22 Sep 10:16:42 - [info] Server now running at http://127.0.0.1:1880/
22 Sep 10:16:42 - [warn] Encrypted credentials not found
22 Sep 10:16:42 - [info] Starting flows
22 Sep 10:16:42 - [info] Started flows
22 Sep 10:17:31 - [info] Installing module: node-red-contrib-doorbird-ultimate, version: 1.1.0
22 Sep 10:17:36 - [info] Installed module: node-red-contrib-doorbird-ultimate
22 Sep 10:17:36 - [info] Added node types:
22 Sep 10:17:36 - [info]  - node-red-contrib-doorbird-ultimate:doorbird-config
22 Sep 10:17:36 - [info]  - node-red-contrib-doorbird-ultimate:doorbird-info
22 Sep 10:17:36 - [info]  - node-red-contrib-doorbird-ultimate:doorbird-open
22 Sep 10:17:36 - [info]  - node-red-contrib-doorbird-ultimate:ui_doorbird-ui-image
22 Sep 10:17:36 - [info]  - node-red-contrib-doorbird-ultimate:ui_doorbird-ui-video
22 Sep 10:17:36 - [info]  - node-red-contrib-doorbird-ultimate:doorbird-ring
22 Sep 10:17:36 - [info]  - node-red-contrib-doorbird-ultimate:doorbird-motion
22 Sep 10:17:36 - [info]  - node-red-contrib-doorbird-ultimate:doorbird-light
22 Sep 10:18:40 - [info] Stopping flows
22 Sep 10:18:40 - [info] Stopped flows
22 Sep 10:18:40 - [info] Updated flows
22 Sep 10:18:40 - [info] Starting flows
22 Sep 10:18:40 - [info] Started flows

**Comment by ihrigb** [comment]
This looks to me, like you do not even receive the broadcasts. Anything from preventing this? (Firewall, Network / VLANs, anything else)

**Comment by Diddlik** [comment]
I tested the ports unter windows, it seems that the listener does not open the ports:
![grafik](https://user-images.githubusercontent.com/6010713/191699606-753b8ed9-a656-48f3-b68c-8e639702c12c.png)

**Comment by Diddlik** [comment]
> This looks to me, like you do not even receive the broadcasts. Anything from preventing this? (Firewall, Network / VLANs, anything else)

It is just local network, without vlans etc.
By the way: udp nodes from node red gets broadcast on this ports.

**Comment by Diddlik** [comment]
![grafik](https://user-images.githubusercontent.com/6010713/191700171-585587b3-05d0-4a88-a43b-b12efbc86ed6.png)

**Comment by ihrigb** [comment]
The fact that it did not open a port helped. I found a small bug and will provide a fix shortly!

**Comment by ihrigb** [comment]
@Diddlik please update to version `1.1.1`.
