### ISSUE TITLE
Events are triggered twice

### ISSUE THREAD

**Issue by Diddlik** [ihrigb/node-red-contrib-doorbird-ultimate#9]
I have a ring event, when it rings it is triggered twice

![grafik](https://user-images.githubusercontent.com/6010713/195337097-96636d10-3af6-4608-8381-64a225849e87.png)

**Comment by ihrigb** [comment]
Hi @Diddlik,

this is actually expected. The Doorbird API doc states this:

> After an event occurred, the DoorBird sends multiple identical UDP-Broadcasts on the ports 6524 and 35344 for every user and every connected device.

(https://www.doorbird.com/downloads/api_lan.pdf?rev=0.28, Page 28)

I have in mind to add an option to suppress this, so lets use this issue as a tracker. The underlying lib already has an option for this!

https://github.com/ihrigb/node-doorbird/commit/bef7736f0124d4619972d6dcc32e377fc4dd8f6d

**Comment by Diddlik** [comment]
ah, that's nice that it would be possible.
Otherwise my automation fails the women acceptance criterion 😂😂😂

**Comment by Diddlik** [comment]
@ihrigb Hallo Benjamin, do you have maybe any updates  to this topic?

**Comment by ihrigb** [comment]
Available now since `v1.2.0`
